version: "3"
services:
  backend_a:
    build:
      context: ./backend
    ports:
      - "8000:8080"
  backend_b:
    build:
      context: ./backend
    ports:
      - "8001:8080"
  krakend:
    image: devopsfaith/krakend:custom
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8080:8080"
    depends_on:
      - backend_a
      - backend_b